### ISSUE TITLE
Problem with UA security when connecting to a Siemens SPS 1500

### ISSUE THREAD

**Issue by eagle275** [technosoftware-gmbh/opc-ua-bundle-net-standard#24]
Hello,

I am tasked with connecting to a Siemens SPS 1500. A coworker setup the SPS, I wrote some small program which is already running in said SPS. When using OPC Expert I can see the opc variables I configured.
But when I try to connect your simple client to the SPS I get error(s)

`Technosoftware .NET Core OPC UA Simple Client`
` 1 - Create an Application Configuration.`
` 2 - Discover endpoints of opc.tcp://10.255.192.221:4840/.`
`    Selected endpoint uses: Basic256`
` 3 - Create a session with OPC UA server.`
`Exception: One or more errors occurred. (Certificate chain validation incomplete.`
`SubjectName: O=Siemens, C=DE, CN=ibn-plc/OPCUA-1-5`
`IssuerName: O=Siemens, C=DE, CN=Siemens TIA Project(rVnB5NUZ5EGyLuKCOi27sQ))`

afterwards the simple client exits with Code 19.

the 2 lines about subjectname / issuername are correct and show what my coworker setup.

What do I need to do to continue reading from the SPS?

**Comment by technosoftware** [comment]
Hello,

If the subject name / issuer name are different, like it looks here, the certificate validation assumes a certificate from a certificate authority and not a self-signed certificate. In that case it checks all Issuers and only gives this exception if the issuer list is empty.

I assume it is a self-signed certificate. In that case subject name and issuer name should be identical.

Hope that helps.

**Comment by technosoftware** [comment]
Assuming that the question is answered I am closing this issue. Let us know if the question is still open.
